import streamlit as st
import requests

st.set_page_config(page_title="NEXUS - Attack Simulator", page_icon="⚡", layout="wide")

BACKEND_URL = "http://127.0.0.1:8000"

st.title("⚡ NEXUS Telemetry & Attack Simulator")
st.caption("Generate normal activity or trigger simulated insider/zero-day attack vectors to test backend detection.")

st.divider()

col1, col2 = st.columns(2)

with col1:
    st.subheader("🚨 Pre-packaged Attack Simulations")
    st.write("Trigger automated attack patterns generated by purpose-built endpoints.")
    
    target_user = st.text_input("Target User ID", value="usr_attacker_01", key="sim_user")
    
    if st.button("🔥 Run Auth Failure Burst (Brute-Force)", use_container_width=True):
        try:
            res = requests.post(f"{BACKEND_URL}/simulate-error?user_id={target_user}")
            if res.status_code == 200:
                st.success(f"Simulation Executed! Result: {res.json()}")
            else:
                st.error(f"Error {res.status_code}: {res.text}")
        except Exception as e:
            st.error(f"Failed to connect to backend: {e}")

    if st.button("🌊 Run Event Flood (DoS / Scraping)", use_container_width=True):
        try:
            res = requests.post(f"{BACKEND_URL}/simulate-burst?user_id={target_user}")
            if res.status_code == 200:
                st.success(f"Simulation Executed! Result: {res.json()}")
            else:
                st.error(f"Error {res.status_code}: {res.text}")
        except Exception as e:
            st.error(f"Failed to connect to backend: {e}")

    if st.button("📦 Run Payload Size Spike (Data Exfiltration)", use_container_width=True):
        try:
            res = requests.post(f"{BACKEND_URL}/simulate-spike?user_id={target_user}")
            if res.status_code == 200:
                st.success(f"Simulation Executed! Score: {res.json().get('anomaly_score')}")
                st.json(res.json())
            else:
                st.error(f"Error {res.status_code}: {res.text}")
        except Exception as e:
            st.error(f"Failed to connect to backend: {e}")

with col2:
    st.subheader("✍️ Custom Live Event Ingestion")
    st.write("Send custom events directly to the `POST /events` scoring pipeline.")
    
    with st.form("custom_event_form"):
        user_id = st.text_input("User ID", value="usr_normal_02")
        event_type = st.selectbox("Event Type", ["FILE_ACCESS", "AUTH_LOGIN", "API_CALL", "PRIVILEGE_ESCALATION", "PROCESS_SPAWN"])
        privilege_level = st.slider("Privilege Level (1-5)", 1, 5, 1)
        bytes_transferred = st.number_input("Payload Size (Bytes)", value=512)
        
        submitted = st.form_submit_button("Submit Event to Engine", use_container_width=True)
        
        if submitted:
            payload = {
                "user_id": user_id,
                "event_type": event_type,
                "payload": {
                    "privilege_level": privilege_level,
                    "bytes_transferred": bytes_transferred
                }
            }
            try:
                res = requests.post(f"{BACKEND_URL}/events", json=payload)
                if res.status_code == 200:
                    st.success("Event Ingested Successfully!")
                    st.json(res.json())
                else:
                    st.error(f"Error {res.status_code}: {res.text}")
            except Exception as e:
                st.error(f"Connection failed: {e}")